server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment-routh
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**

        - id: payment-routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
#            - Cookie=username,yhk
#            - Header=X-Request-Id, \d+

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
